apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-app
spec:
  serviceName: "flask-headless"
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: flask-stateful-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
